added new rpc to get all span data
coralogix/cx-api-tracing pull request #34
Opened 2023-04-30 08:45 UTC by doronmovsho

2023-05-08 08:23 UTC, NimrodAvni78 requested changes

2023-05-08 08:23 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +  google.protobuf.Int32Value graph_id = 2;
you probably dont want graphId since you need to get all graphs in the same request no?

2023-05-08 08:23 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +message GetAllSpanDataResult {
using this?

2023-05-08 08:23 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +  GetSpanGraphResponse span_graph_data = 4;
this might need to be `repeated` if your fetching multiple graphs

2023-05-08 08:23 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +message GetAllSpanDataRequest {
maybe something like `GetSpansScreenData` or something?

2023-05-08 08:31 UTC, doronmovsho commented on com/coralogix/tracing/v1/spans_service.proto
> +  google.protobuf.Int32Value graph_id = 2;
nope, just of specific graph, like the result of `getSpanGraph`.
the "all span data" might be confusing, it's just the concatenation of the 4 different queries in use today - `getSpans`, `getSpansCount`, `getSpansFilter` and `getSpanGraph`

2023-05-08 08:32 UTC, doronmovsho commented on com/coralogix/tracing/v1/spans_service.proto
> +  GetSpanGraphResponse span_graph_data = 4;
returns a specific graph, like the `getSpanGraph` response

2023-05-08 08:33 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +message GetAllSpanDataResult {
its not used anywhere in the protobuf tho

2023-05-08 08:34 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +  GetSpanGraphResponse span_graph_data = 4;
look above

2023-05-08 08:34 UTC, doronmovsho commented on com/coralogix/tracing/v1/spans_service.proto
> +message GetAllSpanDataResult {
it will be used in `ws-tracing` :) 
a PR that will follow soon

2023-05-08 08:39 UTC, NimrodAvni78 commented on com/coralogix/tracing/v1/spans_service.proto
> +message GetAllSpanDataResult {
if its used only there then just have an interface inside the code, no need to expose it in the protobuf schema

2023-05-11 11:57 UTC, doronmovsho commented on com/coralogix/tracing/v1/spans_service.proto
> +message GetAllSpanDataRequest {
@Matan-Gabriel  changed allSpan to fullSpan, can i get an approve? :)

2023-05-11 12:07 UTC, Matan-Gabriel approved these changes

2023-05-11 12:22 UTC, merged